# Generated by Django 3.2.13 on 2022-06-04 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='descripton',
            new_name='description',
        ),
    ]
